"""Generate components/ui/ui_i18n_tables.c from the translations in this folder.

Each lang_*.py module defines LANGS = {code: {...}} with
  wday     7 weekday names, Sunday first, capitalized (they start the date line)
  mon      12 month names in the form used after a day number ("28 septembrie", "28. září")
  date_wd  the date line with weekday, tokens {w} {d} {m}, e.g. "{w}, {d} {m}"
  date     the same without weekday, e.g. "{d} {m}"
  s        UI strings by STR_ id without the prefix; every id of ui_priv.h except the ones in
           OPTIONAL must be present (missing optional ones fall back to English at run time)

The watch picks a language by code ("de", also "de-at"); ALIASES map extra codes to a table.
Run:  python tools/i18n/gen_i18n.py
"""

from __future__ import annotations

import importlib
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
FW = HERE.parent.parent
PRIV_H = FW / "components" / "ui" / "ui_priv.h"
OUT = FW / "components" / "ui" / "ui_i18n_tables.c"
WEB_OUT = FW.parent / "web" / "src" / "watchDates.ts"
MODULES = ["lang_en", "lang_west", "lang_north", "lang_central", "lang_east"]
OPTIONAL = {"CARE"}  # brand names: the English text is used everywhere
FORMAT_IDS = {"NOTICE_FMT", "STARTS_IN_FMT"}  # printf formats with exactly one %s
ALIASES = {"nb": "no", "nn": "no"}


def string_ids() -> list[str]:
    src = PRIV_H.read_text(encoding="utf-8")
    body = src[src.index("typedef enum {\n    STR_SETTINGS"): src.index("STR__COUNT")]
    return re.findall(r"STR_(\w+),", body)


def c_str(s: str) -> str:
    out = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{out}"'


def check(code: str, lang: dict, ids: list[str]) -> list[str]:
    errors = []
    if len(lang["wday"]) != 7 or len(lang["mon"]) != 12:
        errors.append(f"{code}: need 7 weekdays and 12 months")
    for key in ("date_wd", "date"):
        for tok in ("{d}", "{m}"):
            if tok not in lang[key]:
                errors.append(f"{code}: {key} lacks {tok}")
    if "{w}" not in lang["date_wd"]:
        errors.append(f"{code}: date_wd lacks {{w}}")
    s = lang["s"]
    for sid in ids:
        if sid not in s and sid not in OPTIONAL:
            errors.append(f"{code}: missing {sid}")
    for sid in s:
        if sid not in ids:
            errors.append(f"{code}: unknown id {sid}")
    for sid, text in s.items():
        if sid in FORMAT_IDS:
            if text.count("%s") != 1 or "%" in text.replace("%s", ""):
                errors.append(f"{code}: {sid} needs exactly one %s")
        elif "%" in text:
            errors.append(f"{code}: {sid} must not contain %")
    return errors


def main() -> int:
    sys.path.insert(0, str(HERE))
    ids = string_ids()
    langs: dict[str, dict] = {}
    for m in MODULES:
        for code, lang in importlib.import_module(m).LANGS.items():
            if code in langs:
                print(f"duplicate language {code}")
                return 1
            langs[code] = lang
    errors = [e for code, lang in langs.items() for e in check(code, lang, ids)]
    if errors:
        print("\n".join(errors))
        return 1

    lines = [
        "/*",
        " * ola - UI translations. GENERATED by tools/i18n/gen_i18n.py from tools/i18n/lang_*.py:",
        " * edit those files and run the script; do not edit this file by hand.",
        " */",
        '#include "ui_priv.h"',
        "",
        "const ui_lang_t ui_langs[] = {",
    ]
    for code, lang in langs.items():
        lines.append(f"    {{ .code = {c_str(code)},")
        lines.append("      .wday = { " + ", ".join(c_str(w) for w in lang["wday"]) + " },")
        lines.append("      .mon = { " + ", ".join(c_str(m) for m in lang["mon"]) + " },")
        lines.append(f"      .date_wd = {c_str(lang['date_wd'])}, .date = {c_str(lang['date'])},")
        lines.append("      .str = {")
        for sid in ids:
            if sid in lang["s"]:
                lines.append(f"        [STR_{sid}] = {c_str(lang['s'][sid])},")
        lines.append("      } },")
    lines += [
        "};",
        "",
        "const size_t ui_lang_count = sizeof(ui_langs) / sizeof(ui_langs[0]);",
        "",
        "const ui_lang_alias_t ui_lang_aliases[] = {",
        *[f"    {{ {c_str(a)}, {c_str(t)} }}," for a, t in ALIASES.items()],
        "    { NULL, NULL },",
        "};",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{OUT.relative_to(FW)}: {len(langs)} languages, {len(ids)} strings")

    # The web app's watch preview draws the date line exactly like the watch.
    dates = {
        code: {k: lang[k] for k in ("wday", "mon", "date_wd", "date")} for code, lang in langs.items()
    }
    web = [
        "// The watch's date line (weekday / month names and order), per language. GENERATED by",
        "// firmware/tools/i18n/gen_i18n.py from firmware/tools/i18n/lang_*.py - do not edit by hand.",
        "",
        "export interface WatchDateLang {",
        "  wday: string[];",
        "  mon: string[];",
        "  date_wd: string;",
        "  date: string;",
        "}",
        "",
        f"export const WATCH_DATE_LANGS: Record<string, WatchDateLang> = {json.dumps(dates, ensure_ascii=False, indent=2)};",
        "",
        f"export const WATCH_LANG_ALIASES: Record<string, string> = {json.dumps(ALIASES)};",
        "",
    ]
    WEB_OUT.write_text("\n".join(web), encoding="utf-8", newline="\n")
    print(f"{WEB_OUT.relative_to(FW.parent)}: dates for the web watch preview")
    return 0


if __name__ == "__main__":
    sys.exit(main())
