/*
 * ola - UI language: menus, messages and the date line.
 *
 * The texts live in ui_i18n_tables.c, generated by tools/i18n/gen_i18n.py
 * from tools/i18n/lang_*.py (English plus the European languages and
 * Ukrainian). The watch language follows the `language` setting (the same one
 * the owner picks in the web app or on the watch):
 *  - a code with a table -> that language ("de-at" uses "de", "nb" uses "no");
 *  - "auto" -> the language of the last reply (stt_result.language /
 *    tts_start.language) if it has a table;
 *  - otherwise English. A string a language lacks also falls back to English.
 * Style: the weekday starts the date line and is capitalized; month names
 * follow each language's running-text convention. Romanian uses the
 * comma-below letters ș ț (U+0219 / U+021B).
 */
#include <stdio.h>
#include <string.h>
#include "ui_priv.h"

static char s_setting_lang[SETTINGS_LANG_MAX] = "auto";
static char s_reply_lang[SETTINGS_LANG_MAX];
static const ui_lang_t *s_lang = &ui_langs[0];      /* ui_langs[0] is English */

/* Table for a code ("de", also "de-at" / "pt-br" / an alias), or NULL. */
static const ui_lang_t *find_lang(const char *code)
{
    if (!code || !code[0]) {
        return NULL;
    }
    char base[8];
    size_t n = strcspn(code, "-_");
    if (n >= sizeof(base)) {
        return NULL;
    }
    memcpy(base, code, n);
    base[n] = '\0';
    for (const ui_lang_alias_t *a = ui_lang_aliases; a->code; a++) {
        if (strcmp(a->code, base) == 0) {
            strlcpy(base, a->lang, sizeof(base));
            break;
        }
    }
    for (size_t i = 0; i < ui_lang_count; i++) {
        if (strcmp(ui_langs[i].code, base) == 0) {
            return &ui_langs[i];
        }
    }
    return NULL;
}

/* Recompute the UI language; returns true if it changed. */
static bool update_lang(void)
{
    const ui_lang_t *l = strcmp(s_setting_lang, "auto") == 0 ? find_lang(s_reply_lang)
                                                              : find_lang(s_setting_lang);
    if (!l) {
        l = &ui_langs[0];
    }
    bool changed = l != s_lang;
    s_lang = l;
    return changed;
}

bool ui_i18n_set_language(const char *lang)
{
    strlcpy(s_setting_lang, (lang && lang[0]) ? lang : "auto", sizeof(s_setting_lang));
    return update_lang();
}

bool ui_i18n_set_reply_language(const char *lang)
{
    if (!lang || !lang[0]) {
        return false;
    }
    strlcpy(s_reply_lang, lang, sizeof(s_reply_lang));
    return update_lang();
}

const char *ui_str(ui_str_t id)
{
    if (id >= STR__COUNT) {
        return "";
    }
    const char *s = s_lang->str[id];
    if (!s) {
        s = ui_langs[0].str[id];
    }
    return s ? s : "";
}

const char *ui_weekday_name(int wday)
{
    return (wday >= 0 && wday < 7) ? s_lang->wday[wday] : "";
}

/* Fill a "{w}, {d} {m}" pattern. */
void ui_format_date(char *buf, size_t len, int wday, int mday, int mon, bool with_weekday)
{
    const char *p = with_weekday && wday >= 0 && wday < 7 ? s_lang->date_wd : s_lang->date;
    size_t o = 0;
    if (!len) {
        return;
    }
    while (*p && o + 1 < len) {
        const char *part = NULL;
        char num[8];
        if (strncmp(p, "{w}", 3) == 0) {
            part = ui_weekday_name(wday);
        } else if (strncmp(p, "{m}", 3) == 0) {
            part = (mon >= 0 && mon < 12) ? s_lang->mon[mon] : "";
        } else if (strncmp(p, "{d}", 3) == 0) {
            snprintf(num, sizeof(num), "%d", mday);
            part = num;
        }
        if (part) {
            size_t n = strlcpy(buf + o, part, len - o);
            o = n < len - o ? o + n : len - 1;
            p += 3;
        } else {
            buf[o++] = *p++;
        }
    }
    buf[o] = '\0';
}
