"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 13:03:51.643337
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_username'), ['username'], unique=True)

    op.create_table('devices',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('hw_model', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('fw_version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('paired_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('last_seen_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('last_ip', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('battery_pct', sa.Integer(), nullable=True),
    sa.Column('charging', sa.Boolean(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_token_hash'), ['token_hash'], unique=False)

    op.create_table('firmware_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('firmware_releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firmware_releases_version'), ['version'], unique=False)

    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('last_activity_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_device_id'), ['device_id'], unique=False)

    op.create_table('device_settings',
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('turn_no', sa.Integer(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('user_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assistant_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stt_provider', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('tts_provider', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('stt_ms', sa.Integer(), nullable=True),
    sa.Column('llm_first_token_ms', sa.Integer(), nullable=True),
    sa.Column('tts_first_audio_ms', sa.Integer(), nullable=True),
    sa.Column('ttfa_server_ms', sa.Integer(), nullable=True),
    sa.Column('ttfa_device_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('finished_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turns_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turns_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_turns_device_id'), ['device_id'], unique=False)

    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_turn_id'), ['turn_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_records_turn_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_device_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_created_at'))

    op.drop_table('usage_records')
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turns_device_id'))
        batch_op.drop_index(batch_op.f('ix_turns_created_at'))
        batch_op.drop_index(batch_op.f('ix_turns_conversation_id'))

    op.drop_table('turns')
    op.drop_table('device_settings')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_device_id'))

    op.drop_table('conversations')
    op.drop_table('pricing_rules')
    op.drop_table('personas')
    with op.batch_alter_table('firmware_releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firmware_releases_version'))

    op.drop_table('firmware_releases')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_token_hash'))

    op.drop_table('devices')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_username'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
