// The watch's date line (weekday / month names and order), per language. GENERATED by
// firmware/tools/i18n/gen_i18n.py from firmware/tools/i18n/lang_*.py - do not edit by hand.

export interface WatchDateLang {
  wday: string[];
  mon: string[];
  date_wd: string;
  date: string;
}

export const WATCH_DATE_LANGS: Record<string, WatchDateLang> = {
  "en": {
    "wday": [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday"
    ],
    "mon": [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December"
    ],
    "date_wd": "{w}, {d} {m}",
    "date": "{d} {m}"
  },
  "ro": {
    "wday": [
      "Duminică",
      "Luni",
      "Marți",
      "Miercuri",
      "Joi",
      "Vineri",
      "Sâmbătă"
    ],
    "mon": [
      "ianuarie",
      "februarie",
      "martie",
      "aprilie",
      "mai",
      "iunie",
      "iulie",
      "august",
      "septembrie",
      "octombrie",
      "noiembrie",
      "decembrie"
    ],
    "date_wd": "{w}, {d} {m}",
    "date": "{d} {m}"
  },
  "de": {
    "wday": [
      "Sonntag",
      "Montag",
      "Dienstag",
      "Mittwoch",
      "Donnerstag",
      "Freitag",
      "Samstag"
    ],
    "mon": [
      "Januar",
      "Februar",
      "März",
      "April",
      "Mai",
      "Juni",
      "Juli",
      "August",
      "September",
      "Oktober",
      "November",
      "Dezember"
    ],
    "date_wd": "{w}, {d}. {m}",
    "date": "{d}. {m}"
  },
  "fr": {
    "wday": [
      "Dimanche",
      "Lundi",
      "Mardi",
      "Mercredi",
      "Jeudi",
      "Vendredi",
      "Samedi"
    ],
    "mon": [
      "janvier",
      "février",
      "mars",
      "avril",
      "mai",
      "juin",
      "juillet",
      "août",
      "septembre",
      "octobre",
      "novembre",
      "décembre"
    ],
    "date_wd": "{w} {d} {m}",
    "date": "{d} {m}"
  },
  "es": {
    "wday": [
      "Domingo",
      "Lunes",
      "Martes",
      "Miércoles",
      "Jueves",
      "Viernes",
      "Sábado"
    ],
    "mon": [
      "enero",
      "febrero",
      "marzo",
      "abril",
      "mayo",
      "junio",
      "julio",
      "agosto",
      "septiembre",
      "octubre",
      "noviembre",
      "diciembre"
    ],
    "date_wd": "{w}, {d} de {m}",
    "date": "{d} de {m}"
  },
  "it": {
    "wday": [
      "Domenica",
      "Lunedì",
      "Martedì",
      "Mercoledì",
      "Giovedì",
      "Venerdì",
      "Sabato"
    ],
    "mon": [
      "gennaio",
      "febbraio",
      "marzo",
      "aprile",
      "maggio",
      "giugno",
      "luglio",
      "agosto",
      "settembre",
      "ottobre",
      "novembre",
      "dicembre"
    ],
    "date_wd": "{w} {d} {m}",
    "date": "{d} {m}"
  },
  "pt": {
    "wday": [
      "Domingo",
      "Segunda-feira",
      "Terça-feira",
      "Quarta-feira",
      "Quinta-feira",
      "Sexta-feira",
      "Sábado"
    ],
    "mon": [
      "janeiro",
      "fevereiro",
      "março",
      "abril",
      "maio",
      "junho",
      "julho",
      "agosto",
      "setembro",
      "outubro",
      "novembro",
      "dezembro"
    ],
    "date_wd": "{w}, {d} de {m}",
    "date": "{d} de {m}"
  },
  "nl": {
    "wday": [
      "Zondag",
      "Maandag",
      "Dinsdag",
      "Woensdag",
      "Donderdag",
      "Vrijdag",
      "Zaterdag"
    ],
    "mon": [
      "januari",
      "februari",
      "maart",
      "april",
      "mei",
      "juni",
      "juli",
      "augustus",
      "september",
      "oktober",
      "november",
      "december"
    ],
    "date_wd": "{w} {d} {m}",
    "date": "{d} {m}"
  },
  "ca": {
    "wday": [
      "Diumenge",
      "Dilluns",
      "Dimarts",
      "Dimecres",
      "Dijous",
      "Divendres",
      "Dissabte"
    ],
    "mon": [
      "de gener",
      "de febrer",
      "de març",
      "d’abril",
      "de maig",
      "de juny",
      "de juliol",
      "d’agost",
      "de setembre",
      "d’octubre",
      "de novembre",
      "de desembre"
    ],
    "date_wd": "{w}, {d} {m}",
    "date": "{d} {m}"
  },
  "gl": {
    "wday": [
      "Domingo",
      "Luns",
      "Martes",
      "Mércores",
      "Xoves",
      "Venres",
      "Sábado"
    ],
    "mon": [
      "xaneiro",
      "febreiro",
      "marzo",
      "abril",
      "maio",
      "xuño",
      "xullo",
      "agosto",
      "setembro",
      "outubro",
      "novembro",
      "decembro"
    ],
    "date_wd": "{w}, {d} de {m}",
    "date": "{d} de {m}"
  },
  "sv": {
    "wday": [
      "Söndag",
      "Måndag",
      "Tisdag",
      "Onsdag",
      "Torsdag",
      "Fredag",
      "Lördag"
    ],
    "mon": [
      "januari",
      "februari",
      "mars",
      "april",
      "maj",
      "juni",
      "juli",
      "augusti",
      "september",
      "oktober",
      "november",
      "december"
    ],
    "date_wd": "{w} {d} {m}",
    "date": "{d} {m}"
  },
  "da": {
    "wday": [
      "Søndag",
      "Mandag",
      "Tirsdag",
      "Onsdag",
      "Torsdag",
      "Fredag",
      "Lørdag"
    ],
    "mon": [
      "januar",
      "februar",
      "marts",
      "april",
      "maj",
      "juni",
      "juli",
      "august",
      "september",
      "oktober",
      "november",
      "december"
    ],
    "date_wd": "{w} {d}. {m}",
    "date": "{d}. {m}"
  },
  "no": {
    "wday": [
      "Søndag",
      "Mandag",
      "Tirsdag",
      "Onsdag",
      "Torsdag",
      "Fredag",
      "Lørdag"
    ],
    "mon": [
      "januar",
      "februar",
      "mars",
      "april",
      "mai",
      "juni",
      "juli",
      "august",
      "september",
      "oktober",
      "november",
      "desember"
    ],
    "date_wd": "{w} {d}. {m}",
    "date": "{d}. {m}"
  },
  "is": {
    "wday": [
      "Sunnudagur",
      "Mánudagur",
      "Þriðjudagur",
      "Miðvikudagur",
      "Fimmtudagur",
      "Föstudagur",
      "Laugardagur"
    ],
    "mon": [
      "janúar",
      "febrúar",
      "mars",
      "apríl",
      "maí",
      "júní",
      "júlí",
      "ágúst",
      "september",
      "október",
      "nóvember",
      "desember"
    ],
    "date_wd": "{w} {d}. {m}",
    "date": "{d}. {m}"
  },
  "fi": {
    "wday": [
      "Sunnuntai",
      "Maanantai",
      "Tiistai",
      "Keskiviikko",
      "Torstai",
      "Perjantai",
      "Lauantai"
    ],
    "mon": [
      "tammikuuta",
      "helmikuuta",
      "maaliskuuta",
      "huhtikuuta",
      "toukokuuta",
      "kesäkuuta",
      "heinäkuuta",
      "elokuuta",
      "syyskuuta",
      "lokakuuta",
      "marraskuuta",
      "joulukuuta"
    ],
    "date_wd": "{w} {d}. {m}",
    "date": "{d}. {m}"
  },
  "et": {
    "wday": [
      "Pühapäev",
      "Esmaspäev",
      "Teisipäev",
      "Kolmapäev",
      "Neljapäev",
      "Reede",
      "Laupäev"
    ],
    "mon": [
      "jaanuar",
      "veebruar",
      "märts",
      "aprill",
      "mai",
      "juuni",
      "juuli",
      "august",
      "september",
      "oktoober",
      "november",
      "detsember"
    ],
    "date_wd": "{w}, {d}. {m}",
    "date": "{d}. {m}"
  },
  "lv": {
    "wday": [
      "Svētdiena",
      "Pirmdiena",
      "Otrdiena",
      "Trešdiena",
      "Ceturtdiena",
      "Piektdiena",
      "Sestdiena"
    ],
    "mon": [
      "janvāris",
      "februāris",
      "marts",
      "aprīlis",
      "maijs",
      "jūnijs",
      "jūlijs",
      "augusts",
      "septembris",
      "oktobris",
      "novembris",
      "decembris"
    ],
    "date_wd": "{w}, {d}. {m}",
    "date": "{d}. {m}"
  },
  "lt": {
    "wday": [
      "Sekmadienis",
      "Pirmadienis",
      "Antradienis",
      "Trečiadienis",
      "Ketvirtadienis",
      "Penktadienis",
      "Šeštadienis"
    ],
    "mon": [
      "sausio",
      "vasario",
      "kovo",
      "balandžio",
      "gegužės",
      "birželio",
      "liepos",
      "rugpjūčio",
      "rugsėjo",
      "spalio",
      "lapkričio",
      "gruodžio"
    ],
    "date_wd": "{w}, {m} {d} d.",
    "date": "{m} {d} d."
  },
  "cy": {
    "wday": [
      "Dydd Sul",
      "Dydd Llun",
      "Dydd Mawrth",
      "Dydd Mercher",
      "Dydd Iau",
      "Dydd Gwener",
      "Dydd Sadwrn"
    ],
    "mon": [
      "Ionawr",
      "Chwefror",
      "Mawrth",
      "Ebrill",
      "Mai",
      "Mehefin",
      "Gorffennaf",
      "Awst",
      "Medi",
      "Hydref",
      "Tachwedd",
      "Rhagfyr"
    ],
    "date_wd": "{w}, {d} {m}",
    "date": "{d} {m}"
  },
  "pl": {
    "wday": [
      "Niedziela",
      "Poniedziałek",
      "Wtorek",
      "Środa",
      "Czwartek",
      "Piątek",
      "Sobota"
    ],
    "mon": [
      "stycznia",
      "lutego",
      "marca",
      "kwietnia",
      "maja",
      "czerwca",
      "lipca",
      "sierpnia",
      "września",
      "października",
      "listopada",
      "grudnia"
    ],
    "date_wd": "{w}, {d} {m}",
    "date": "{d} {m}"
  },
  "cs": {
    "wday": [
      "Neděle",
      "Pondělí",
      "Úterý",
      "Středa",
      "Čtvrtek",
      "Pátek",
      "Sobota"
    ],
    "mon": [
      "ledna",
      "února",
      "března",
      "dubna",
      "května",
      "června",
      "července",
      "srpna",
      "září",
      "října",
      "listopadu",
      "prosince"
    ],
    "date_wd": "{w} {d}. {m}",
    "date": "{d}. {m}"
  },
  "sk": {
    "wday": [
      "Nedeľa",
      "Pondelok",
      "Utorok",
      "Streda",
      "Štvrtok",
      "Piatok",
      "Sobota"
    ],
    "mon": [
      "januára",
      "februára",
      "marca",
      "apríla",
      "mája",
      "júna",
      "júla",
      "augusta",
      "septembra",
      "októbra",
      "novembra",
      "decembra"
    ],
    "date_wd": "{w}, {d}. {m}",
    "date": "{d}. {m}"
  },
  "hu": {
    "wday": [
      "Vasárnap",
      "Hétfő",
      "Kedd",
      "Szerda",
      "Csütörtök",
      "Péntek",
      "Szombat"
    ],
    "mon": [
      "január",
      "február",
      "március",
      "április",
      "május",
      "június",
      "július",
      "augusztus",
      "szeptember",
      "október",
      "november",
      "december"
    ],
    "date_wd": "{w}, {m} {d}.",
    "date": "{m} {d}."
  },
  "sl": {
    "wday": [
      "Nedelja",
      "Ponedeljek",
      "Torek",
      "Sreda",
      "Četrtek",
      "Petek",
      "Sobota"
    ],
    "mon": [
      "januar",
      "februar",
      "marec",
      "april",
      "maj",
      "junij",
      "julij",
      "avgust",
      "september",
      "oktober",
      "november",
      "december"
    ],
    "date_wd": "{w}, {d}. {m}",
    "date": "{d}. {m}"
  },
  "hr": {
    "wday": [
      "Nedjelja",
      "Ponedjeljak",
      "Utorak",
      "Srijeda",
      "Četvrtak",
      "Petak",
      "Subota"
    ],
    "mon": [
      "siječnja",
      "veljače",
      "ožujka",
      "travnja",
      "svibnja",
      "lipnja",
      "srpnja",
      "kolovoza",
      "rujna",
      "listopada",
      "studenoga",
      "prosinca"
    ],
    "date_wd": "{w}, {d}. {m}",
    "date": "{d}. {m}"
  },
  "bs": {
    "wday": [
      "Nedjelja",
      "Ponedjeljak",
      "Utorak",
      "Srijeda",
      "Četvrtak",
      "Petak",
      "Subota"
    ],
    "mon": [
      "januar",
      "februar",
      "mart",
      "april",
      "maj",
      "juni",
      "juli",
      "august",
      "septembar",
      "oktobar",
      "novembar",
      "decembar"
    ],
    "date_wd": "{w}, {d}. {m}",
    "date": "{d}. {m}"
  },
  "sr": {
    "wday": [
      "Nedelja",
      "Ponedeljak",
      "Utorak",
      "Sreda",
      "Četvrtak",
      "Petak",
      "Subota"
    ],
    "mon": [
      "januar",
      "februar",
      "mart",
      "april",
      "maj",
      "jun",
      "jul",
      "avgust",
      "septembar",
      "oktobar",
      "novembar",
      "decembar"
    ],
    "date_wd": "{w}, {d}. {m}",
    "date": "{d}. {m}"
  },
  "el": {
    "wday": [
      "Κυριακή",
      "Δευτέρα",
      "Τρίτη",
      "Τετάρτη",
      "Πέμπτη",
      "Παρασκευή",
      "Σάββατο"
    ],
    "mon": [
      "Ιανουαρίου",
      "Φεβρουαρίου",
      "Μαρτίου",
      "Απριλίου",
      "Μαΐου",
      "Ιουνίου",
      "Ιουλίου",
      "Αυγούστου",
      "Σεπτεμβρίου",
      "Οκτωβρίου",
      "Νοεμβρίου",
      "Δεκεμβρίου"
    ],
    "date_wd": "{w}, {d} {m}",
    "date": "{d} {m}"
  },
  "bg": {
    "wday": [
      "Неделя",
      "Понеделник",
      "Вторник",
      "Сряда",
      "Четвъртък",
      "Петък",
      "Събота"
    ],
    "mon": [
      "януари",
      "февруари",
      "март",
      "април",
      "май",
      "юни",
      "юли",
      "август",
      "септември",
      "октомври",
      "ноември",
      "декември"
    ],
    "date_wd": "{w}, {d} {m}",
    "date": "{d} {m}"
  },
  "mk": {
    "wday": [
      "Недела",
      "Понеделник",
      "Вторник",
      "Среда",
      "Четврток",
      "Петок",
      "Сабота"
    ],
    "mon": [
      "јануари",
      "февруари",
      "март",
      "април",
      "мај",
      "јуни",
      "јули",
      "август",
      "септември",
      "октомври",
      "ноември",
      "декември"
    ],
    "date_wd": "{w}, {d} {m}",
    "date": "{d} {m}"
  },
  "uk": {
    "wday": [
      "Неділя",
      "Понеділок",
      "Вівторок",
      "Середа",
      "Четвер",
      "П’ятниця",
      "Субота"
    ],
    "mon": [
      "січня",
      "лютого",
      "березня",
      "квітня",
      "травня",
      "червня",
      "липня",
      "серпня",
      "вересня",
      "жовтня",
      "листопада",
      "грудня"
    ],
    "date_wd": "{w}, {d} {m}",
    "date": "{d} {m}"
  }
};

export const WATCH_LANG_ALIASES: Record<string, string> = {"nb": "no", "nn": "no"};
